### ISSUE TITLE
Nullpointer Exception - get Searchview to event listner searchView.setOnQueryTextListener() to solve this issue

### ISSUE THREAD

**Issue by rajendrachauhan** [Agraphie/MaterialSearchView#1]
In Material Search view - when release mode get Searchview null pointer Exception to solve this issue

**Comment by Agraphie** [comment]
Hi,

can you please provide some sample code on how to reproduce this error? In general I use this library in [connactivities](https://play.google.com/store/apps/details?id=net.connactivities.app.android) in release build and don't have this error.

EDIT: Are you using 1.0.3 or 1.0.0? I just noticed that in the README an old version was used.

**Comment by rajendrachauhan** [comment]
searchView.setOnQueryTextListener(new MaterialSearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                //Do some magic
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                //Do some magic         
                return false;
            }
        });

Above code issue in release mode app so can you help me ?

**Comment by Agraphie** [comment]
Can you make sure that you are using version 1.0.3? As I cannot reproduce this issue, can you provide a more complete example or sample project?

**Comment by rajendrachauhan** [comment]
i tried to many time but not solved that isuue...?
my gradle file - compile 'de.clemenskeppler:MaterialSearchView:1.0.3'

**Comment by Agraphie** [comment]
Ok thanks for checking. Can you please post your XML file as well? Can you please show the code on where you are calling the search view? Are you adding the view dynamically and not through XML?

**Comment by rajendrachauhan** [comment]
My xml layout file is :
<RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/color_white" />

        <de.clemenskeppler.materialsearchview.MaterialSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:visibility="gone"
            app:hideOnKeyboardClose="false" />


</RelativeLayout>

and i put menu file code as below:
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
     
    <item
        android:id="@+id/action_search"
        android:icon="@mipmap/ic_search"
        android:orderInCategory="100"
        android:title="@string/abc_search_hint"
        app:showAsAction="collapseActionView|always" />
  
    <item
        android:id="@+id/setting"
        android:icon="@drawable/icon_setting"
        android:title="@string/action_setting" />
</menu>

and using through XML,
so solved my issue. what is problem ?

**Comment by Agraphie** [comment]
So it is working for you now?
I guess it works because you added the view through XML instead of through java code. Can you confirm please?
